/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type GeneratedColumn<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface BlockedIpList {
  created_at: Date | null;
  deleted_at: Date | null;
  id: Buffer;
  ip_address: string | null;
  updated_at: Date | null;
}

export interface Transaction {
  created_at: Date | null;
  deleted_at: Date | null;
  id: Buffer;
  status: number | null;
  updated_at: Date | null;
}

export interface DB {
  blocked_ip_list: BlockedIpList;
  transactions: Transaction;
}
